#!/bin/sh

if [[ $# -lt 1 ]]
then
    echo "Usage: ./shell <filename>(without .py)"
else
    if [[ "$1" = "help" ]]
    then
        echo "This script will execute modules from examples directory"
    else
        python3 -m examples.$1
    fi
fi